language: node_js
node_js:
  - "stable"
  - "4.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --dev
script:
  - node --harmony-proxies node_modules/.bin/istanbul -- cover node_modules/mocha/bin/_mocha index.spec.js && codecov

